const fs = require('fs');
const { execSync } = require('child_process');

const hash = execSync('git rev-parse --short HEAD').toString().trim();
const date = new Date().toISOString();

fs.writeFileSync('src/version.ts',
`// Auto-generated by update-version.js
export const ENGINE_VERSION = '${hash}';
export const ENGINE_BUILD_DATE = '${date}';
`);

console.log('Version:', hash);
