export const VERSION = '0.1.0';

export { Engine } from './Engine';
export { Vec2, Vec3, Matrix2d, Rect, Polygon } from './math/index';
export { EventEmitter } from './events/index';
export { Entity, Component, System } from './ecs/index';
export { Unit, Player, Item, Projectile, Prop, Region, Sensor, CombatSystem } from './game/index';
export { Clock } from './time/index';
export { PhysicsWorld, RigidBody } from './physics/index';
export type { BodyDef, ColliderDef } from './physics/index';
export { PhysicsWorld3d, RigidBody3d } from './physics/index';
export type { BodyDef3d, ColliderDef3d } from './physics/index';
export { CollisionCategory, DefaultCollisionMask, categoryForEntityType } from './physics/index';
export { PhysicsActionQueue } from './physics/index';
export type { PhysicsAction, PhysicsActionType } from './physics/index';
export { createWallBodiesFromMap } from './physics/index';
export { Map2d, TileMap, Pathfinding } from './map/index';
export type { TileData } from './map/index';
export { ScriptEngine, TriggerManager, ActionRunner, ConditionEvaluator, VariableStore, ScriptAPI } from './scripting/index';
export type { TriggerContext, ActionVars, ConditionOperator, ConditionNode } from './scripting/index';
export { GameMode } from './GameMode';
export type { Mode } from './GameMode';
export { GameLoader } from './GameLoader';
export type { GameData, ScriptDef } from './GameLoader';
export { GameMigrator } from './GameMigrator';
export type { MigratedGameData } from './GameMigrator';
export { Serializer, DeltaCompressor, InputBuffer, WorldSnapshot, InterestManagement, MessageType } from './network/index';
export { CoordinateUtils } from './CoordinateUtils';
export { LocalGameSession } from './LocalGameSession';
export type { LocalGameConfig } from './LocalGameSession';
